@echo off
call .venv\Scripts\activate
echo Starting KSRTC-HyRO Services...

echo Starting Frontend on Port 8000...
start "Frontend (Port 8000)" python -m http.server 8000

echo Starting Flask Backend on Port 5001...
start "Flask Backend (Port 5001)" python src/app.py

echo Starting OSRM Server on Port 5000...
:: Use %~dp0 to get the script's directory, ensuring the path is correct even if spaces exist
docker run -t -i -p 5000:5000 -v "%~dp0osrm_data:/data" osrm/osrm-backend osrm-routed /data/kerala-latest.osrm
