@echo off
echo Starting remaining services...

echo Launching Backend...
start "Backend" cmd /k python src/app.py

echo Launching OSRM...
start "OSRM" cmd /k docker run -t -i -p 5000:5000 -v "%~dp0osrm_data:/data" osrm/osrm-backend osrm-routed /data/kerala-latest.osrm
