import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import joblib
import os

def train_model():
    """
    Trains a passenger demand prediction model using the correct, most up-to-date
    dataset and saves it to a file.
    """
    print("--- Training Passenger Demand Model ---")
    
    # Corrected file path to the dataset generated by the overpy script
    data_path = 'data/kochi_overpy_bus_data.csv' 
    if not os.path.exists(data_path):
        print(f"❌ Error: Dataset not found at {data_path}")
        print("Please run 'python src/generate_from_osm.py' first.")
        return

    df = pd.read_csv(data_path)

    # We will only use features that are available at prediction time
    features = ['hour_of_day', 'day_of_week', 'is_peak_hour']
    target = 'passenger_count'

    X = df[features]
    y = df[target]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    print("Training RandomForestRegressor...")
    model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)

    # Save the trained model
    model_path = 'models/passenger_demand_model.pkl'
    joblib.dump(model, model_path)
    print(f"✅ Model successfully trained and saved to {model_path}")

if __name__ == "__main__":
    train_model()

